services:
  app:
    build: .
    image: medicare-flow-api:latest
    container_name: medicare-flow-api
    ports:
      - "8081:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
